web:
  build: .
  container_name: biddingservice
  ports:
    - "9090:9090"
  links:
    - mongobiddingservice:mongobiddingservice
  command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar

mongobiddingservice:
  image: mongo:latest
  container_name: mongobiddingservice
  ports:
    - "27018:27017"
